export default
[{"MST_ID":1,"MST_Name":"Kaunas"},
{"MST_ID":2,"MST_Name":"Klaipėdos r. "},
{"MST_ID":3,"MST_Name":"Kupiškio r."},
{"MST_ID":4,"MST_Name":"Kaišiadorių r."},
{"MST_ID":5,"MST_Name":"Vilnius"},
{"MST_ID":6,"MST_Name":"Vilkaviškio r."},
{"MST_ID":7,"MST_Name":"Klaipėda"},
{"MST_ID":8,"MST_Name":"Kedainių r."},
{"MST_ID":9,"MST_Name":"Tauragės r."},
{"MST_ID":10,"MST_Name":"Šilutės r."},
{"MST_ID":11,"MST_Name":"Alytus"},
{"MST_ID":12,"MST_Name":"Plungės r."},
{"MST_ID":13,"MST_Name":"Vilniaus r."},
{"MST_ID":14,"MST_Name":"Birštonas"},
{"MST_ID":15,"MST_Name":"Neringa"},
{"MST_ID":16,"MST_Name":"Šilalės r."},
{"MST_ID":17,"MST_Name":"Zarasų r."},
{"MST_ID":18,"MST_Name":"Utenos r."},
{"MST_ID":19,"MST_Name":"Druskininkai"},
{"MST_ID":20,"MST_Name":"Palanga"},
{"MST_ID":21,"MST_Name":"Kauno r."},
{"MST_ID":22,"MST_Name":"Panevežys"},
{"MST_ID":23,"MST_Name":"Ignalinos r."},
{"MST_ID":24,"MST_Name":"Varėnos r."},
{"MST_ID":25,"MST_Name":"Kretingos r."},
{"MST_ID":26,"MST_Name":"Jonavos r."},
{"MST_ID":27,"MST_Name":"Anykšcių r."},
{"MST_ID":28,"MST_Name":"Pasvalio r."},
{"MST_ID":29,"MST_Name":"Kelmės r."},
{"MST_ID":30,"MST_Name":"Švenčionių r."},
{"MST_ID":31,"MST_Name":"Telšių r."},
{"MST_ID":32,"MST_Name":"Trakų r."},
{"MST_ID":33,"MST_Name":"Biržų r."},
{"MST_ID":34,"MST_Name":"Panevežio r."},
{"MST_ID":35,"MST_Name":"Joniškio r."},
{"MST_ID":36,"MST_Name":"Akmenės r."},
{"MST_ID":37,"MST_Name":"Šiaulių r."},
{"MST_ID":38,"MST_Name":"Radviliškio r."},
{"MST_ID":39,"MST_Name":"Marijampolė"},
{"MST_ID":40,"MST_Name":"Lazdijų r."},
{"MST_ID":41,"MST_Name":"Mažeikių r."},
{"MST_ID":42,"MST_Name":"Skuodo r."},
{"MST_ID":43,"MST_Name":"Jurbarko r."},
{"MST_ID":44,"MST_Name":"Ukmerges r."},
{"MST_ID":45,"MST_Name":"Alytaus r."},
{"MST_ID":46,"MST_Name":"Raseinių r."},
{"MST_ID":47,"MST_Name":"Prienų r."},
{"MST_ID":48,"MST_Name":"Marijampolės r."},
{"MST_ID":49,"MST_Name":"Šakių r."},
{"MST_ID":50,"MST_Name":"Šalčininkų r."},
{"MST_ID":51,"MST_Name":"Pakruojo r."},
{"MST_ID":52,"MST_Name":"Molėtų r."},
{"MST_ID":53,"MST_Name":"Rokiškio r."},
{"MST_ID":54,"MST_Name":"Visaginas"},
{"MST_ID":55,"MST_Name":"Šiauliai"},
{"MST_ID":56,"MST_Name":"Širvintų r."},
{"MST_ID":57,"MST_Name":"Akmenė"},
{"MST_ID":58,"MST_Name":"Anykščiai"},
{"MST_ID":59,"MST_Name":"Ariogala"},
{"MST_ID":60,"MST_Name":"Baltoji Vokė"},
{"MST_ID":61,"MST_Name":"Biržai"},
{"MST_ID":62,"MST_Name":"Daugai"},
{"MST_ID":63,"MST_Name":"Dukštas"},
{"MST_ID":64,"MST_Name":"Dusetos"},
{"MST_ID":65,"MST_Name":"Eišiškės"},
{"MST_ID":66,"MST_Name":"Elektrėnai"},
{"MST_ID":67,"MST_Name":"Ežerėlis"},
{"MST_ID":68,"MST_Name":"Gargždai"},
{"MST_ID":69,"MST_Name":"Garliava"},
{"MST_ID":70,"MST_Name":"Gelgaudiškis"},
{"MST_ID":71,"MST_Name":"Grigiškės"},
{"MST_ID":72,"MST_Name":"Ignalina"},
{"MST_ID":73,"MST_Name":"Jieznas"},
{"MST_ID":74,"MST_Name":"Jonava"},
{"MST_ID":75,"MST_Name":"Joniškėlis"},
{"MST_ID":76,"MST_Name":"Joniškis"},
{"MST_ID":77,"MST_Name":"Jurbarkas"},
{"MST_ID":78,"MST_Name":"Kaišiadorys"},
{"MST_ID":79,"MST_Name":"Kalvarija"},
{"MST_ID":80,"MST_Name":"Kavarskas"},
{"MST_ID":81,"MST_Name":"Kazlų Rūda"},
{"MST_ID":82,"MST_Name":"Kėdainiai"},
{"MST_ID":83,"MST_Name":"Kelmė"},
{"MST_ID":84,"MST_Name":"Kybartai"},
{"MST_ID":85,"MST_Name":"Kretinga"},
{"MST_ID":86,"MST_Name":"Kudirkos Naumiestis"},
{"MST_ID":87,"MST_Name":"Kupiškis"},
{"MST_ID":88,"MST_Name":"Kuršėnai"},
{"MST_ID":89,"MST_Name":"Lazdijai"},
{"MST_ID":90,"MST_Name":"Lentvaris"},
{"MST_ID":91,"MST_Name":"Linkuva"},
{"MST_ID":92,"MST_Name":"Mažeikiai"},
{"MST_ID":93,"MST_Name":"Molėtai"},
{"MST_ID":94,"MST_Name":"Naujoji Akmene"},
{"MST_ID":95,"MST_Name":"Nemenčinė"},
{"MST_ID":96,"MST_Name":"Obeliai"},
{"MST_ID":97,"MST_Name":"Pabradė"},
{"MST_ID":98,"MST_Name":"Pagėgiai"},
{"MST_ID":99,"MST_Name":"Pakruojis"},
{"MST_ID":100,"MST_Name":"Pandelys"},
{"MST_ID":101,"MST_Name":"Panemunė"},
{"MST_ID":102,"MST_Name":"Pasvalys"},
{"MST_ID":103,"MST_Name":"Plungė"},
{"MST_ID":104,"MST_Name":"Priekulė"},
{"MST_ID":105,"MST_Name":"Prienai"},
{"MST_ID":106,"MST_Name":"Radviliškis"},
{"MST_ID":107,"MST_Name":"Ramygala"},
{"MST_ID":108,"MST_Name":"Radviliškis"},
{"MST_ID":109,"MST_Name":"Ramygala"},
{"MST_ID":110,"MST_Name":"Raseiniai"},
{"MST_ID":111,"MST_Name":"Rietavas"},
{"MST_ID":112,"MST_Name":"Rokiškis"},
{"MST_ID":113,"MST_Name":"Rūdiškės"},
{"MST_ID":114,"MST_Name":"Salantai"},
{"MST_ID":115,"MST_Name":"Seda"},
{"MST_ID":116,"MST_Name":"Simnas"},
{"MST_ID":117,"MST_Name":"Skaudvilė"},
{"MST_ID":118,"MST_Name":"Skuodas"},
{"MST_ID":119,"MST_Name":"Smalininkai"},
{"MST_ID":120,"MST_Name":"Subačius"},
{"MST_ID":121,"MST_Name":"Šakiai"},
{"MST_ID":122,"MST_Name":"Šalčininkai"},
{"MST_ID":123,"MST_Name":"Šeduva"},
{"MST_ID":124,"MST_Name":"Šilalė"},
{"MST_ID":125,"MST_Name":"Šilutė"},
{"MST_ID":126,"MST_Name":"Širvintos"},
{"MST_ID":127,"MST_Name":"Švenčionėliai"},
{"MST_ID":128,"MST_Name":"Švenčionys"},
{"MST_ID":129,"MST_Name":"Tauragė"},
{"MST_ID":130,"MST_Name":"Telšiai"},
{"MST_ID":131,"MST_Name":"Tytuvėnai"},
{"MST_ID":132,"MST_Name":"Trakai"},
{"MST_ID":133,"MST_Name":"Troškūnai"},
{"MST_ID":134,"MST_Name":"Ukmergė"},
{"MST_ID":135,"MST_Name":"Utena"},
{"MST_ID":136,"MST_Name":"Užventis"},
{"MST_ID":137,"MST_Name":"Vabalninkas"},
{"MST_ID":138,"MST_Name":"Varėna"},
{"MST_ID":139,"MST_Name":"Varniai"},
{"MST_ID":140,"MST_Name":"Veisiejai"},
{"MST_ID":141,"MST_Name":"Venta"},
{"MST_ID":142,"MST_Name":"Viekšniai"},
{"MST_ID":143,"MST_Name":"Vievis"},
{"MST_ID":144,"MST_Name":"Vilkaviškis"},
{"MST_ID":145,"MST_Name":"Vilkija"},
{"MST_ID":146,"MST_Name":"Virbalis"},
{"MST_ID":147,"MST_Name":"Zarasai"},
{"MST_ID":148,"MST_Name":"Žagarė"},
{"MST_ID":149,"MST_Name":"Žiežmariai"}]