export default
[{"ALPHA_2_CODE":"AD","LT_SHORT_NAME":"Andora"},
{"ALPHA_2_CODE":"AE","LT_SHORT_NAME":"Jungtiniai Arabų Emyratai"},
{"ALPHA_2_CODE":"AF","LT_SHORT_NAME":"Afganistanas"},
{"ALPHA_2_CODE":"AG","LT_SHORT_NAME":"Antigva ir Barbuda"},
{"ALPHA_2_CODE":"AI","LT_SHORT_NAME":"Angilija"},
{"ALPHA_2_CODE":"AL","LT_SHORT_NAME":"Albanija"},
{"ALPHA_2_CODE":"AM","LT_SHORT_NAME":"Armėnija"},
{"ALPHA_2_CODE":"AO","LT_SHORT_NAME":"Angola"},
{"ALPHA_2_CODE":"AQ","LT_SHORT_NAME":"Antarktika"},
{"ALPHA_2_CODE":"AR","LT_SHORT_NAME":"Argentina"},
{"ALPHA_2_CODE":"AS","LT_SHORT_NAME":"Amerikos Samoa"},
{"ALPHA_2_CODE":"AT","LT_SHORT_NAME":"Austrija"},
{"ALPHA_2_CODE":"AU","LT_SHORT_NAME":"Australija"},
{"ALPHA_2_CODE":"AW","LT_SHORT_NAME":"Aruba"},
{"ALPHA_2_CODE":"AX","LT_SHORT_NAME":"Alandų salos"},
{"ALPHA_2_CODE":"AZ","LT_SHORT_NAME":"Azerbaidžanas"},
{"ALPHA_2_CODE":"BA","LT_SHORT_NAME":"Bosnija ir Hercegovina"},
{"ALPHA_2_CODE":"BB","LT_SHORT_NAME":"Barbadosas"},
{"ALPHA_2_CODE":"BD","LT_SHORT_NAME":"Bangladešas"},
{"ALPHA_2_CODE":"BE","LT_SHORT_NAME":"Belgija"},
{"ALPHA_2_CODE":"BF","LT_SHORT_NAME":"Burkina Faso"},
{"ALPHA_2_CODE":"BG","LT_SHORT_NAME":"Bulgarija"},
{"ALPHA_2_CODE":"BH","LT_SHORT_NAME":"Bahreinas"},
{"ALPHA_2_CODE":"BI","LT_SHORT_NAME":"Burundis"},
{"ALPHA_2_CODE":"BY","LT_SHORT_NAME":"Baltarusija"},
{"ALPHA_2_CODE":"BJ","LT_SHORT_NAME":"Beninas"},
{"ALPHA_2_CODE":"BL","LT_SHORT_NAME":"Saint Barthelemy"},
{"ALPHA_2_CODE":"BM","LT_SHORT_NAME":"Bermudai"},
{"ALPHA_2_CODE":"BN","LT_SHORT_NAME":"Brunei Darussalam"},
{"ALPHA_2_CODE":"BO","LT_SHORT_NAME":"Bolivija"},
{"ALPHA_2_CODE":"BQ","LT_SHORT_NAME":"Bonaire, Sint Eustatius ir Saba"},
{"ALPHA_2_CODE":"BR","LT_SHORT_NAME":"Brazilija"},
{"ALPHA_2_CODE":"BS","LT_SHORT_NAME":"Bahamai"},
{"ALPHA_2_CODE":"BT","LT_SHORT_NAME":"Butanas"},
{"ALPHA_2_CODE":"BV","LT_SHORT_NAME":"Bouvet sala"},
{"ALPHA_2_CODE":"BW","LT_SHORT_NAME":"Botsvana"},
{"ALPHA_2_CODE":"BZ","LT_SHORT_NAME":"Belizas"},
{"ALPHA_2_CODE":"CA","LT_SHORT_NAME":"Kanada"},
{"ALPHA_2_CODE":"CC","LT_SHORT_NAME":"Kokosų (Kilingo) salos"},
{"ALPHA_2_CODE":"CD","LT_SHORT_NAME":"Kongas (Demokratinė Respublika)"},
{"ALPHA_2_CODE":"CF","LT_SHORT_NAME":"Centrinės Afrikos Respublika"},
{"ALPHA_2_CODE":"CG","LT_SHORT_NAME":"Kongas"},
{"ALPHA_2_CODE":"CH","LT_SHORT_NAME":"Šveicarija"},
{"ALPHA_2_CODE":"CI","LT_SHORT_NAME":"Cote d'Ivoire"},
{"ALPHA_2_CODE":"CY","LT_SHORT_NAME":"Kipras"},
{"ALPHA_2_CODE":"CK","LT_SHORT_NAME":"Kuko salos"},
{"ALPHA_2_CODE":"CL","LT_SHORT_NAME":"Cile"},
{"ALPHA_2_CODE":"CM","LT_SHORT_NAME":"Kamerūnas"},
{"ALPHA_2_CODE":"CN","LT_SHORT_NAME":"Kinija"},
{"ALPHA_2_CODE":"CO","LT_SHORT_NAME":"Kolumbija"},
{"ALPHA_2_CODE":"CR","LT_SHORT_NAME":"Kosta Rika"},
{"ALPHA_2_CODE":"CU","LT_SHORT_NAME":"Kuba"},
{"ALPHA_2_CODE":"CV","LT_SHORT_NAME":"Cabo Verde"},
{"ALPHA_2_CODE":"CW","LT_SHORT_NAME":"Kurasao"},
{"ALPHA_2_CODE":"CX","LT_SHORT_NAME":"Kaledų sala"},
{"ALPHA_2_CODE":"CZ","LT_SHORT_NAME":"Čekija"},
{"ALPHA_2_CODE":"DE","LT_SHORT_NAME":"Vokietija"},
{"ALPHA_2_CODE":"DJ","LT_SHORT_NAME":"Džibutis"},
{"ALPHA_2_CODE":"DK","LT_SHORT_NAME":"Danija"},
{"ALPHA_2_CODE":"DM","LT_SHORT_NAME":"Dominika"},
{"ALPHA_2_CODE":"DO","LT_SHORT_NAME":"Dominikos Respublika"},
{"ALPHA_2_CODE":"DZ","LT_SHORT_NAME":"Alžyras"},
{"ALPHA_2_CODE":"EC","LT_SHORT_NAME":"Ekvadoras"},
{"ALPHA_2_CODE":"EE","LT_SHORT_NAME":"Estija"},
{"ALPHA_2_CODE":"EG","LT_SHORT_NAME":"Egiptas"},
{"ALPHA_2_CODE":"EH","LT_SHORT_NAME":"Vakarų Sachara"},
{"ALPHA_2_CODE":"ER","LT_SHORT_NAME":"Eritrėja"},
{"ALPHA_2_CODE":"ES","LT_SHORT_NAME":"Ispanija"},
{"ALPHA_2_CODE":"ET","LT_SHORT_NAME":"Etiopija"},
{"ALPHA_2_CODE":"FI","LT_SHORT_NAME":"Suomija"},
{"ALPHA_2_CODE":"FJ","LT_SHORT_NAME":"Fidžis"},
{"ALPHA_2_CODE":"FK","LT_SHORT_NAME":"Folklando salos"},
{"ALPHA_2_CODE":"FM","LT_SHORT_NAME":"Mikronezija"},
{"ALPHA_2_CODE":"FO","LT_SHORT_NAME":"Farerų salos"},
{"ALPHA_2_CODE":"FR","LT_SHORT_NAME":"Prancūzija"},
{"ALPHA_2_CODE":"GA","LT_SHORT_NAME":"Gabonas"},
{"ALPHA_2_CODE":"GB","LT_SHORT_NAME":"Jungtinė Karalystė"},
{"ALPHA_2_CODE":"GD","LT_SHORT_NAME":"Grenada"},
{"ALPHA_2_CODE":"GE","LT_SHORT_NAME":"Gruzija"},
{"ALPHA_2_CODE":"GF","LT_SHORT_NAME":"Prancūzijos Gviana"},
{"ALPHA_2_CODE":"GG","LT_SHORT_NAME":"Gernsis"},
{"ALPHA_2_CODE":"GH","LT_SHORT_NAME":"Gana"},
{"ALPHA_2_CODE":"GI","LT_SHORT_NAME":"Gibraltaras"},
{"ALPHA_2_CODE":"GY","LT_SHORT_NAME":"Gajana"},
{"ALPHA_2_CODE":"GL","LT_SHORT_NAME":"Grenlandija"},
{"ALPHA_2_CODE":"GM","LT_SHORT_NAME":"Gambija"},
{"ALPHA_2_CODE":"GN","LT_SHORT_NAME":"Gvinėja"},
{"ALPHA_2_CODE":"GP","LT_SHORT_NAME":"Gvadelupa"},
{"ALPHA_2_CODE":"GQ","LT_SHORT_NAME":"Pusiaujo Gvinėja"},
{"ALPHA_2_CODE":"GR","LT_SHORT_NAME":"Graikija"},
{"ALPHA_2_CODE":"GS","LT_SHORT_NAME":"Pietų Džordžija ir Pietų Sandvico salos"},
{"ALPHA_2_CODE":"GT","LT_SHORT_NAME":"Gvatemala"},
{"ALPHA_2_CODE":"GU","LT_SHORT_NAME":"Guamas"},
{"ALPHA_2_CODE":"GW","LT_SHORT_NAME":"Gvinėja Bisau"},
{"ALPHA_2_CODE":"HK","LT_SHORT_NAME":"Honkongas"},
{"ALPHA_2_CODE":"HM","LT_SHORT_NAME":"Heard sala ir McDonaldo salos"},
{"ALPHA_2_CODE":"HN","LT_SHORT_NAME":"Honduras"},
{"ALPHA_2_CODE":"HR","LT_SHORT_NAME":"Kroatija"},
{"ALPHA_2_CODE":"HT","LT_SHORT_NAME":"Haitis"},
{"ALPHA_2_CODE":"HU","LT_SHORT_NAME":"Vengrija"},
{"ALPHA_2_CODE":"ID","LT_SHORT_NAME":"Indonezija"},
{"ALPHA_2_CODE":"IE","LT_SHORT_NAME":"Airija"},
{"ALPHA_2_CODE":"IL","LT_SHORT_NAME":"Izraelis"},
{"ALPHA_2_CODE":"IM","LT_SHORT_NAME":"Meno sala"},
{"ALPHA_2_CODE":"IN","LT_SHORT_NAME":"Indija"},
{"ALPHA_2_CODE":"IO","LT_SHORT_NAME":"Indijos vandenyno britų teritorija"},
{"ALPHA_2_CODE":"IQ","LT_SHORT_NAME":"Irakas"},
{"ALPHA_2_CODE":"IR","LT_SHORT_NAME":"Iranas (Islamo Respublika)"},
{"ALPHA_2_CODE":"IS","LT_SHORT_NAME":"Islandija"},
{"ALPHA_2_CODE":"IT","LT_SHORT_NAME":"Italija"},
{"ALPHA_2_CODE":"YE","LT_SHORT_NAME":"Jemenas"},
{"ALPHA_2_CODE":"YT","LT_SHORT_NAME":"Majotas"},
{"ALPHA_2_CODE":"JE","LT_SHORT_NAME":"Džersis"},
{"ALPHA_2_CODE":"JM","LT_SHORT_NAME":"Jamaika"},
{"ALPHA_2_CODE":"JO","LT_SHORT_NAME":"Jordanija"},
{"ALPHA_2_CODE":"JP","LT_SHORT_NAME":"Japonija"},
{"ALPHA_2_CODE":"KE","LT_SHORT_NAME":"Kenija"},
{"ALPHA_2_CODE":"KG","LT_SHORT_NAME":"Kirgizija"},
{"ALPHA_2_CODE":"KH","LT_SHORT_NAME":"Kambodža"},
{"ALPHA_2_CODE":"KI","LT_SHORT_NAME":"Kiribatis"},
{"ALPHA_2_CODE":"KY","LT_SHORT_NAME":"Kaimanų salos"},
{"ALPHA_2_CODE":"KM","LT_SHORT_NAME":"Komorai"},
{"ALPHA_2_CODE":"KN","LT_SHORT_NAME":"Sent Kitsas ir Nevis"},
{"ALPHA_2_CODE":"KP","LT_SHORT_NAME":"Korėja (Liaudies Demokratinė Respublika)"},
{"ALPHA_2_CODE":"KR","LT_SHORT_NAME":"Korėja (Respublika)"},
{"ALPHA_2_CODE":"KW","LT_SHORT_NAME":"Kuveitas"},
{"ALPHA_2_CODE":"KZ","LT_SHORT_NAME":"Kazachstanas"},
{"ALPHA_2_CODE":"LA","LT_SHORT_NAME":"Laoso Liaudies Demokratinė Respublika"},
{"ALPHA_2_CODE":"LB","LT_SHORT_NAME":"Libanas"},
{"ALPHA_2_CODE":"LC","LT_SHORT_NAME":"Sent Lusija"},
{"ALPHA_2_CODE":"LI","LT_SHORT_NAME":"Lichtenšteinas"},
{"ALPHA_2_CODE":"LY","LT_SHORT_NAME":"Libija"},
{"ALPHA_2_CODE":"LK","LT_SHORT_NAME":"Šri Lanka"},
{"ALPHA_2_CODE":"LR","LT_SHORT_NAME":"Liberija"},
{"ALPHA_2_CODE":"LS","LT_SHORT_NAME":"Lesotas"},
{"ALPHA_2_CODE":"LT","LT_SHORT_NAME":"Lietuva"},
{"ALPHA_2_CODE":"LU","LT_SHORT_NAME":"Liuksemburgas"},
{"ALPHA_2_CODE":"LV","LT_SHORT_NAME":"Latvija"},
{"ALPHA_2_CODE":"MA","LT_SHORT_NAME":"Marokas"},
{"ALPHA_2_CODE":"MC","LT_SHORT_NAME":"Monakas"},
{"ALPHA_2_CODE":"MD","LT_SHORT_NAME":"Moldova"},
{"ALPHA_2_CODE":"ME","LT_SHORT_NAME":"Juodkalnija"},
{"ALPHA_2_CODE":"MF","LT_SHORT_NAME":"Saint Martin (prancūzų dalis)"},
{"ALPHA_2_CODE":"MG","LT_SHORT_NAME":"Madagaskaras"},
{"ALPHA_2_CODE":"MH","LT_SHORT_NAME":"Maršalų salos"},
{"ALPHA_2_CODE":"MY","LT_SHORT_NAME":"Malaizija"},
{"ALPHA_2_CODE":"MK","LT_SHORT_NAME":"Makedonija (Buvusioji Jugoslavijos Respublika)"},
{"ALPHA_2_CODE":"ML","LT_SHORT_NAME":"Malis"},
{"ALPHA_2_CODE":"MM","LT_SHORT_NAME":"Mianmaras"},
{"ALPHA_2_CODE":"MN","LT_SHORT_NAME":"Mongolija"},
{"ALPHA_2_CODE":"MO","LT_SHORT_NAME":"Makao"},
{"ALPHA_2_CODE":"MP","LT_SHORT_NAME":"Šiaurės Marianų salos"},
{"ALPHA_2_CODE":"MQ","LT_SHORT_NAME":"Martinika"},
{"ALPHA_2_CODE":"MR","LT_SHORT_NAME":"Mauritanija"},
{"ALPHA_2_CODE":"MS","LT_SHORT_NAME":"Montseratas"},
{"ALPHA_2_CODE":"MT","LT_SHORT_NAME":"Malta"},
{"ALPHA_2_CODE":"MU","LT_SHORT_NAME":"Mauricijus"},
{"ALPHA_2_CODE":"MV","LT_SHORT_NAME":"Maldyvai"},
{"ALPHA_2_CODE":"MW","LT_SHORT_NAME":"Malavis"},
{"ALPHA_2_CODE":"MX","LT_SHORT_NAME":"Meksika"},
{"ALPHA_2_CODE":"MZ","LT_SHORT_NAME":"Mozambikas"},
{"ALPHA_2_CODE":"NA","LT_SHORT_NAME":"Namibija"},
{"ALPHA_2_CODE":"NC","LT_SHORT_NAME":"Naujoji Kaledonija"},
{"ALPHA_2_CODE":"NE","LT_SHORT_NAME":"Nigeris"},
{"ALPHA_2_CODE":"NF","LT_SHORT_NAME":"Norfolko sala"},
{"ALPHA_2_CODE":"NG","LT_SHORT_NAME":"Nigerija"},
{"ALPHA_2_CODE":"NI","LT_SHORT_NAME":"Nikaragva"},
{"ALPHA_2_CODE":"NL","LT_SHORT_NAME":"Olandija"},
{"ALPHA_2_CODE":"NO","LT_SHORT_NAME":"Norvegija"},
{"ALPHA_2_CODE":"NP","LT_SHORT_NAME":"Nepalas"},
{"ALPHA_2_CODE":"NR","LT_SHORT_NAME":"Nauru"},
{"ALPHA_2_CODE":"NU","LT_SHORT_NAME":"Niue"},
{"ALPHA_2_CODE":"NZ","LT_SHORT_NAME":"Naujoji Zelandija"},
{"ALPHA_2_CODE":"OM","LT_SHORT_NAME":"Omanas"},
{"ALPHA_2_CODE":"PA","LT_SHORT_NAME":"Panama"},
{"ALPHA_2_CODE":"PE","LT_SHORT_NAME":"Peru"},
{"ALPHA_2_CODE":"PF","LT_SHORT_NAME":"Prancūzų Polinezija"},
{"ALPHA_2_CODE":"PG","LT_SHORT_NAME":"Papua Naujoji Gvinėja"},
{"ALPHA_2_CODE":"PH","LT_SHORT_NAME":"Filipinai"},
{"ALPHA_2_CODE":"PY","LT_SHORT_NAME":"Paragvajus"},
{"ALPHA_2_CODE":"PK","LT_SHORT_NAME":"Pakistanas"},
{"ALPHA_2_CODE":"PL","LT_SHORT_NAME":"Lenkija"},
{"ALPHA_2_CODE":"PM","LT_SHORT_NAME":"Sen Pjeras ir Mikelonas"},
{"ALPHA_2_CODE":"PN","LT_SHORT_NAME":"Pitkernas"},
{"ALPHA_2_CODE":"PR","LT_SHORT_NAME":"Puerto Rikas"},
{"ALPHA_2_CODE":"PS","LT_SHORT_NAME":"Palestina"},
{"ALPHA_2_CODE":"PT","LT_SHORT_NAME":"Portugalija"},
{"ALPHA_2_CODE":"PW","LT_SHORT_NAME":"Palau"},
{"ALPHA_2_CODE":"QA","LT_SHORT_NAME":"Kataras"},
{"ALPHA_2_CODE":"RE","LT_SHORT_NAME":"Reunionas"},
{"ALPHA_2_CODE":"RO","LT_SHORT_NAME":"Rumunija"},
{"ALPHA_2_CODE":"RS","LT_SHORT_NAME":"Serbija"},
{"ALPHA_2_CODE":"RU","LT_SHORT_NAME":"Rusijos Federacija"},
{"ALPHA_2_CODE":"RW","LT_SHORT_NAME":"Ruanda"},
{"ALPHA_2_CODE":"SA","LT_SHORT_NAME":"Saudo Arabija"},
{"ALPHA_2_CODE":"SB","LT_SHORT_NAME":"Saliamono salos"},
{"ALPHA_2_CODE":"SC","LT_SHORT_NAME":"Seišeliai"},
{"ALPHA_2_CODE":"SD","LT_SHORT_NAME":"Sudanas "},
{"ALPHA_2_CODE":"SE","LT_SHORT_NAME":"Švedija"},
{"ALPHA_2_CODE":"SG","LT_SHORT_NAME":"Singapuras"},
{"ALPHA_2_CODE":"SH","LT_SHORT_NAME":"Šv. Elena, Ascension ir Tristan da Cunha"},
{"ALPHA_2_CODE":"SI","LT_SHORT_NAME":"Slovėnija"},
{"ALPHA_2_CODE":"SY","LT_SHORT_NAME":"Sirijos Arabų Respublika"},
{"ALPHA_2_CODE":"SJ","LT_SHORT_NAME":"Svalbardas ir Janas Majenas"},
{"ALPHA_2_CODE":"SK","LT_SHORT_NAME":"Slovakija"},
{"ALPHA_2_CODE":"SL","LT_SHORT_NAME":"Siera Leonė"},
{"ALPHA_2_CODE":"SM","LT_SHORT_NAME":"San Marinas"},
{"ALPHA_2_CODE":"SN","LT_SHORT_NAME":"Senegalas"},
{"ALPHA_2_CODE":"SO","LT_SHORT_NAME":"Somalis"},
{"ALPHA_2_CODE":"SR","LT_SHORT_NAME":"Surinamas"},
{"ALPHA_2_CODE":"SS","LT_SHORT_NAME":"Pietų Sudanas"},
{"ALPHA_2_CODE":"ST","LT_SHORT_NAME":"San Tome ir Prinsipe"},
{"ALPHA_2_CODE":"SV","LT_SHORT_NAME":"Salvadoras"},
{"ALPHA_2_CODE":"SX","LT_SHORT_NAME":"Sint Maarten (olandu dalis)"},
{"ALPHA_2_CODE":"SZ","LT_SHORT_NAME":"Svazilendas"},
{"ALPHA_2_CODE":"TC","LT_SHORT_NAME":"Turkso ir Caicoso salos"},
{"ALPHA_2_CODE":"TD","LT_SHORT_NAME":"Čadas"},
{"ALPHA_2_CODE":"TF","LT_SHORT_NAME":"Prancūzijos Pietinės teritorijos"},
{"ALPHA_2_CODE":"TG","LT_SHORT_NAME":"Togas"},
{"ALPHA_2_CODE":"TH","LT_SHORT_NAME":"Tailandas"},
{"ALPHA_2_CODE":"TJ","LT_SHORT_NAME":"Tadžikistanas"},
{"ALPHA_2_CODE":"TK","LT_SHORT_NAME":"Tokelau"},
{"ALPHA_2_CODE":"TL","LT_SHORT_NAME":"Timoras-Leste"},
{"ALPHA_2_CODE":"TM","LT_SHORT_NAME":"Turkmenistanas"},
{"ALPHA_2_CODE":"TN","LT_SHORT_NAME":"Tunisas"},
{"ALPHA_2_CODE":"TO","LT_SHORT_NAME":"Tonga"},
{"ALPHA_2_CODE":"TR","LT_SHORT_NAME":"Turkija"},
{"ALPHA_2_CODE":"TT","LT_SHORT_NAME":"Trinidadas ir Tobagas"},
{"ALPHA_2_CODE":"TV","LT_SHORT_NAME":"Tuvalu"},
{"ALPHA_2_CODE":"TW","LT_SHORT_NAME":"Taivanas"},
{"ALPHA_2_CODE":"TZ","LT_SHORT_NAME":"Tanzanija"},
{"ALPHA_2_CODE":"UA","LT_SHORT_NAME":"Ukraina"},
{"ALPHA_2_CODE":"UG","LT_SHORT_NAME":"Uganda"},
{"ALPHA_2_CODE":"UY","LT_SHORT_NAME":"Urugvajus"},
{"ALPHA_2_CODE":"UM","LT_SHORT_NAME":"Mažosios atokios salos JAV"},
{"ALPHA_2_CODE":"US","LT_SHORT_NAME":"Jungtinės Amerikos Valstijos"},
{"ALPHA_2_CODE":"UZ","LT_SHORT_NAME":"Uzbekistanas"},
{"ALPHA_2_CODE":"VA","LT_SHORT_NAME":"Vatikanas"},
{"ALPHA_2_CODE":"VC","LT_SHORT_NAME":"Sent Vinsentas ir Grenadinai"},
{"ALPHA_2_CODE":"VE","LT_SHORT_NAME":"Venesuela"},
{"ALPHA_2_CODE":"VG","LT_SHORT_NAME":"Virginijos salos (britų)"},
{"ALPHA_2_CODE":"VI","LT_SHORT_NAME":"Virginijos salos (JAV)"},
{"ALPHA_2_CODE":"VN","LT_SHORT_NAME":"Vietnamas"},
{"ALPHA_2_CODE":"VU","LT_SHORT_NAME":"Vanuatu"},
{"ALPHA_2_CODE":"WF","LT_SHORT_NAME":"Volisas ir Futuna"},
{"ALPHA_2_CODE":"WS","LT_SHORT_NAME":"Samoa"},
{"ALPHA_2_CODE":"ZA","LT_SHORT_NAME":"Pietų Afrika"},
{"ALPHA_2_CODE":"ZM","LT_SHORT_NAME":"Zambija"},
{"ALPHA_2_CODE":"ZW","LT_SHORT_NAME":"Zimbabvė"}]